### PR TITLE
fix(web): prevent duplicate `network error`

### LINKED ISSUE #1174: [improve]: show errortips only once
After opening [https://flat-web.whiteboard.agora.io](https://flat-web.whiteboard.agora.io), switch to another tab page.

At this time, if you are in a situation where you have no internet, or very poor internet. Wait a few minutes and switch back to the `flat` page.

You can then see a very large number of repeated error messages.

**But really we only need it once.**

图片

https://user-images.githubusercontent.com/8198408/144801797-62b988b6-c664-4ca0-a76b-496446e63db5.mp4

### PR DESCRIPTION
**Pull request by jayeclark**
Signed-off-by: Jay Clark <jay@jayeclark.dev>

Fixes #1174 

The `antd` message component allows messages to be identified by a key. This key enables the content of a specific message to be updated dynamically, but it also ensures that a duplicate message will not be created for the given key. 

Setting the key to be equal to the error message ensures that only one of each type of error message will show at any given time. (For example, only one error with the message "Network Error" will be present, but an error message with different message content _would_ show up, if it occurred in addition to the "Network Error" message.)

(Prior to my changes, when I turned off the wifi and switched between the indicated menu items, two network error messages would appear.)

errormsg

### CODE REVIEW

**Review by hyrious — DISMISSED** [review]

**Review by LitoMore — DISMISSED** [review]

**Comment by BlackHole1** [comment]
Thank you for the PR! I will review it later.

File: web/flat-web/src/components/Tips/ErrorTips.tsx [hunk 1]
```diff
@@ -9,8 +9,8 @@ export const errorTips = (e: unknown): void => {
     }
 
     if (e instanceof ServerRequestError) {
-        void message.error(i18n.t(e.errorMessage));
+        void message.error({ content: i18n.t(e.errorMessage), key: i18n.t(e.errorMessage) });
```
Comment (BlackHole1) [inline web/flat-web/src/components/Tips/ErrorTips.tsx]:
```suggestion
        void message.error({
            content: i18n.t(e.errorMessage),
            key: e.errorCode,
        });
```

File: web/flat-web/src/components/Tips/ErrorTips.tsx [hunk 2]
```diff
@@ -9,8 +9,8 @@ export const errorTips = (e: unknown): void => {
...
     } else {
-        void message.error((e as Error).message);
+        void message.error({ content: (e as Error).message, key: (e as Error).message });
```
Comment (BlackHole1) [inline web/flat-web/src/components/Tips/ErrorTips.tsx]:
```suggestion
        const message = (e as Error).message;
        void message.error({
            content: message,
            key: message
        });
```

**Review by BlackHole1 — CHANGES_REQUESTED** [review]
Just two nitpick to address before landing, but otherwise this looks good.

1. It is better when the value of `key` is `e.errorCode`
2. Forget modify(electron renderer) https://github.com/netless-io/flat/blob/536fc75af70fa69a74bc0f98b8ece55255268677/desktop/renderer-app/src/components/Tips/ErrorTips.tsx#L11-L15

File: web/flat-web/src/components/Tips/ErrorTips.tsx (hunk 1 above)
Comment (jayeclark) [reply web/flat-web/src/components/Tips/ErrorTips.tsx]: @BlackHole1 I used the message itself as the key because I believe it's possible to have different messages generated for the same error code (some are dynamically generated.) You'd know better if that's relevant to the repo or not. If most of the errors being thrown have simple content like 'Network Error' instead of something more complicated (for example something that includes the URL of a resource), it might not be as relevant as I assumed, but I thought I'd at least mention it.

File: web/flat-web/src/components/Tips/ErrorTips.tsx (hunk 2 above)
Comment (jayeclark) [reply web/flat-web/src/components/Tips/ErrorTips.tsx]: Will need to use a different variable than `message` on line 14, but I agree with the general approach.

File: web/flat-web/src/components/Tips/ErrorTips.tsx (hunk 1 above)
Comment (BlackHole1) [reply web/flat-web/src/components/Tips/ErrorTips.tsx]: You have a point.

**Review by BlackHole1 — APPROVED** [review]

**Comment by BlackHole1** [comment]
LGTM

**Comment by BlackHole1** [comment]
hi @jayeclark. Can you check your mail? We have sent you an email with a gift we have prepared.
